# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e63022a44fb58791054769246eba1244ba31f89a47da9e9457428185d2acec228f63a2e34591dc96980f4ec5e5f450e3f42cbf0484cfbdb65cc2eeb9a576a14

test:
  secret_key_base: 949d00bc6a867f87c55d3ec3c9576a5b842a0ee62e52f26b6c6b6dd11e9d4acd7035be526df22ff0763f2021b648e27c5730b33f5ff8c17f2420c9a684210efe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
